### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by zhongzhihao97** [EatingBacon/TableRecognition21#2]
Where does the dataset come from? thanks!

**Comment by timgarrels** [comment]
Hi @zhongzhihao97,
the projects evaluation was based on two datasets:
- The Deco dataset [1], which is an annotated subset of the ENRON Spreasheet Corpus [2]. The ENRON Spreadsheet Corpus was created from spreadsheets found in emails of the ENRON cooperation, which had to publish the mails due to court proceedings.
- The FusTe dataset, which is a subset of the FUSE dataset [3], which is a corpus of spreadsheets found via webcrawling.

Both datasets were pre-processed by removing spreadsheets which are larger than 1MB and by removing spreadsheets which contained hidden rows or columns.


[1] lvis Koci, Maik Thiele, Josephine Rehak, Oscar Romero, and Wolfgang Lehner. 2019. DECO: A Dataset of Annotated Spreadsheets for Layout and Table Recognition. In 2019 International Conference on Document Analysis and Recognition (ICDAR). 1280–1285. https://doi.org/10.1109/ICDAR.2019.00207
[2] Felienne Hermans and Emerson Murphy-Hill. 2015. Enron’s Spreadsheets and Related Emails: A Dataset and Analysis. In 2015 IEEE/ACM 37th IEEE International Conference on Software Engineering, Vol. 2. 7–16. https://doi.org/10.1109/ICSE.
2015.129
[3] Titus Barik, Kevin Lubick, Justin Smith, John Slankas, and Emerson Murphy-Hill. 2015. Fuse: A Reproducible, Extendable, Internet-Scale Corpus of Spreadsheets. 486–489. https://doi.org/10.1109/MSR.2015.70

**Comment by zhongzhihao97** [comment]
Why are the data folder and output folder empty under this project? Can you send me the contents of both folders?

**Comment by timgarrels** [comment]
Hi @zhongzhihao97 ,
The folders are there as placeholders as the code expects that directory structure.
I gave you the dataset names and corresponding references above. I will not re-publish datasets that I did not collect myself. You can find them online.
You can compute the output you are looking for by downloading the mentioned datasets, pre-processing them as described, and running the project.

**Comment by zhongzhihao97** [comment]
ok，thank you！

**Comment by zhongzhihao97** [comment]
Error reported while running specific tests
![21代码问题1](https://user-images.githubusercontent.com/83849440/233937881-06476c76-fcea-44c9-a2fb-90848c8db29e.png)

**Comment by timgarrels** [comment]
I am gonna need a few more details to help you here.
What command did you run, which data did you use, etc.

Also please note that this project was developed and tested only under Linux. From your Path (`D:/`) it seems you are using Windows to run it.
Might be that Windows and its sub-system can manage, but I can not guarantee that

**Comment by timgarrels** [comment]
Your specific error most likely occurred as this project hardcodes the available datasets:

https://github.com/timgarrels/TableRecognition21/blob/main/src/run_cross_validation.py#L23
https://github.com/timgarrels/TableRecognition21/blob/main/src/run_cross_validation.py#L29

You can add your own there, however, you might encounter other problems down the road. I wrote this up in 2021 in a seminar, and this code is thereby not designed to be flexible (yet) :)

**Comment by zhongzhihao97** [comment]
The command I am running is python src/run_cross_validation.py --dataset D:/stxt/tablediscriminate/TableRecognition21-main/src/d1/
Screenshot of file in d1
![image](https://user-images.githubusercontent.com/83849440/233970525-54aa273e-b1cb-46e2-8c87-8c9611df106a.png)

I want to run the following command
![image](https://user-images.githubusercontent.com/83849440/233970606-8c73d63b-11ee-4d76-8d4b-33712acadad2.png)

But the following parts stumped me
![image](https://user-images.githubusercontent.com/83849440/233970653-7b109bbc-4b10-44d7-be9a-f5edc189c037.png)

I don't know how to build a dataset. Can you give me a small example? I want to imitate the example you gave to build a dataset. I am a beginner and I don't understand many things. Thank you for your help!
